; Interrupt Vector Mapping
; Source: "https://github.com/webronen/Shared/blob/fd7909dd559d7c5b82a921b5bef6246ac03cfd53/pdf/AVRxt_ATtiny3224.pdf#page=63"

rjmp setup nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop
reti nop